version: "3.9"
services:
  mongo:
    image: mongo:5.0.3
    container_name: mongo
    restart: always
  backend:
    build: ./backend/
    container_name: backend
    command: ["/start-reload.sh"]
  nginx:
    build: ./nginx/
    container_name: nginx
    ports:
      - "8000:80"
    environment:
      - NGINX_PORT=80
      - SERVER_ADDRESS=localhost
      - SERVER_PORT=8000
    depends_on:
      - backend
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    environment:
      - SERVER_ADDRESS=localhost
      - SERVER_PORT=8000