apiVersion: v1
kind: Service	
metadata:
  name: yourapp-nginx-lb
spec:
  selector:
    app: yourapp-nginx-deployment
  type: LoadBalancer
  ports:
  - nodePort: 31111 
    port: 8000
    targetPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: yourapp-nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yourapp-nginx-deployment
  template:
    metadata:
      labels:
        app: yourapp-nginx-deployment
    spec:
      containers:
      - name: nginx-container
        image: "ardimasp/yourapp-nginx:latest"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 20
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
          - name: SERVER_ADDRESS
            value: "localhost"
          - name: FRONTEND_ADDRESS
            value: "yourapp-frontend-clusterip:8001"
          - name: BACKEND_ADDRESS
            value: "yourapp-backend-clusterip:8002"
  
