apiVersion: v1
kind: Service	
metadata:
  name: yourapp-frontend-clusterip
spec:
  type: ClusterIP
  selector:
    app: yourapp-frontend-deployment
  ports:
  - port: 8001
    targetPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: yourapp-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yourapp-frontend-deployment
  template:
    metadata:
      labels:
        app: yourapp-frontend-deployment
    spec:
      containers:
      - name: yourapp-frontend-container
        image: "ardimasp/yourapp-frontend:latest"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 20
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
